{
 "title": "FI Uplink port - Ingress congestion monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from FIEnvStats with key=domain"
   },
   {
    "name": "fi_id",
    "label": "FI ID",
    "query": "show tag values from FIServerPortStats with key=fi_id where domain =~ /$domain/"
   },
   {
    "name": "uplink",
    "label": "Uplink Port",
    "query": "show tag values from VnicStats with key=pinned_uplink where domain =~ /$domain/ and fi_id =~ /$fi_id/"
   },
   {
    "name": "bp_port",
    "label": "Backplane Port",
    "query": "show tag values from VnicStats with key=iom_backplane_port where domain =~ /$domain/ and fi_id =~ /$fi_id/ and pinned_uplink =~ /$uplink/"
   },
   { "name": "polling_interval", "query": "60" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<table style=\"margin-left: auto; margin-right: auto;\" border=\"0\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' width=\"300\" />\r\n<script>\r\n  document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + \"/your_logo.png\");\r\n</script>\r\n</td>\r\n<td style=\"width: 70%;\">\r\n<h2 style=\"text-align: center;\"><span style=\"text-decoration: underline; color: #299c46;\"><strong>(your name) - UCS Traffic Monitoring - Ingress Congestion</strong></span></h2>\r\n<p style=\"text-align: center;\">This page helps to find the real cause of the ingress traffic congestion on a FI uplink port.</p>\r\n</td>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' alt=\"\" width=\"160\" />\r\n<script>\r\n  document.getElementById('cisco_logo').setAttribute('src', 'http://' + window.location.hostname + \"/cisco_logo.png\");\r\n</script>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"text-align: left;\"></p>"
  },
  {
   "title": "$domain - FI-$fi_id - Uplink - $uplink - Utilization",
   "type": "graph",
   "description": "Assumption: The uplink must be a port-channel. A similar graph can be generated for non-port-channel uplinks",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_port $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIUplinkPortStats",
     "select": [
      [
       { "params": [ "bytes_rx_delta" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8 /[[polling_interval]]" ], "type": "math" },
       { "params": [ "RX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$uplink$/" }
     ]
    }
   ]
  },
  {
   "title": "Backplane port $bp_port - PAUSE frames VS ingress traffic on vIF pinned to uplink $uplink on FI-$fi_id - size to side comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "bp_port"
  },
  {
   "title": "RX PAUSE on backplane port $bp_port",
   "type": "graph",
   "description": "<span style=\"color:orange\">**Use Case**</span>: Find real cause of  ingress traffic congestion on a FI uplink port\n\n<span style=\"color:orange\">**How to use**</span>: Select a UCS domain, FI ID and an uplink port. Select All Backplane ports. Graphs on the left show PAUSE frame activity on IOM backplane ports. PAUSE frames may be exchanged under normal condition also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is probably fine. Pay attention to thousands or tens-of-thousands per second. Millions per second definitely need investigation.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity? For example, does one FI server port (between FI and IOM) stand out than rest of the other ports connected to the same chassis?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicates that high utilization is the cause of congestion.\n\n<span style=\"color:orange\">**Details**</span>: \n- A blade server sends PAUSE frames to IOM backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_chassis $col <-- $tag_to_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "to_service_profile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BackplanePortStats",
     "select": [
      [
       { "params": [ "pause_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "RX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
      { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Traffic from backplane port $bp_port to vIFs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_chassis $tag_service_profile $tag_vif_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vif_name" ], "type": "tag" },
      { "params": [ "service_profile" ], "type": "tag" },
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "VnicStats",
     "select": [
      [
       { "params": [ "bytes_rx_delta" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
       { "params": [ "RX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
      { "condition": "AND", "key": "iom_backplane_port", "operator": "=~", "value": "/^$bp_port$/" },
      { "condition": "AND", "key": "pinned_uplink", "operator": "=~", "value": "/^$uplink$/" }
     ]
    }
   ]
  }
 ]
}