{
 "title": "Locations",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location",
    "query": "show tag values from BladeServers with key=location"
   },
   { "name": "polling_interval", "query": "60.0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<table style=\"margin-left: auto; margin-right: auto;\" border=\"0\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' width=\"300\" />\r\n<script>\r\n  document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + \"/your_logo.png\");\r\n</script>\r\n</td>\r\n<td style=\"width: 70%;\">\r\n<h2 style=\"text-align: center;\"><span style=\"text-decoration: underline; color: #299c46;\"><strong>(your name) - UCS Traffic Monitoring - Location</strong></span></h2>\r\n<p style=\"text-align: center;\">Global or location specific monitoring of the Cisco UCS infrastructure</p>\r\n</td>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' alt=\"\" width=\"160\" />\r\n<script>\r\n  document.getElementById('cisco_logo').setAttribute('src', 'http://' + window.location.hostname + \"/cisco_logo.png\");\r\n</script>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"text-align: left;\"></p>"
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Geo map",
   "type": "larona-epict-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "US_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(last)) from (SELECT last(\"serial\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'US') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "China_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(last)) from (SELECT last(\"serial\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'China') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Italy_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(last)) from (SELECT last(\"serial\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'Italy') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "UK_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(last)) from (SELECT last(\"serial\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'UK') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "US_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'US') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UK_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'UK') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Italy_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'Italy') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "China_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" = 'China') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "US_domain",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(domain)) from (select domain,\"name\" from FIEnvStats WHERE (\"location\" = 'US') AND $timeFilter )",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "UK_domain",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(domain)) from (select domain,\"name\" from FIEnvStats WHERE (\"location\" = 'UK') AND $timeFilter )",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "China_domain",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(domain)) from (select domain,\"name\" from FIEnvStats WHERE (\"location\" = 'China') AND $timeFilter )",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "Italy_domain",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(distinct(domain)) from (select domain,\"name\" from FIEnvStats WHERE (\"location\" = 'Italy') AND $timeFilter )",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "title": "Network and other ports - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Distribution - Operational state - $location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_state\" = 'up') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Not UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_state\" != 'up') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Distribution - Ethernet - Speed - $location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 1) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 10) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 40) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Distribution - Transport - $location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"FC\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"transport\" = 'FC') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Ethernet\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"transport\" = 'Eth') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Distribution - FC - Speed - $location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 4) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 8) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 16) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "# domains - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": " SHOW TAG VALUES CARDINALITY FROM \"autogen\".\"FIEnvStats\" WITH KEY=domain  WHERE (\"location\" =~ /^$location$/)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Blade servers and operational state",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(service_profile) AS \"OK\" from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/ AND \"oper_state\" = 'ok') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "oper_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Operation state - UP" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "oper_state", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(service_profile) AS \"Other\" from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/ AND \"oper_state\" != 'ok') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "oper_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "oper_state", "operator": "!=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "# vFC - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_vFCs\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_vFCs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Server ports - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "# Chassis - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# vEth - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_vEths\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_vEths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution - Operational state - $location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_state\" = 'up') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Not UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_state\" != 'up') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Distribution - operational speed - $location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 1) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 10) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"channel\" != '' AND \"oper_speed\" = 40) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "# blades - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(service_profile) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# CPUs - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_cpus\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# CPU cores - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_cores\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_cores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory - $location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 21 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"memory\") FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Blade servers",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT location as \"Location\", domain as \"Domain\",  chassis as \"Chassis ID\", model as \"Model\", serial as \"Serial\", num_cpus as \"# CPU\", num_cores as \"# Cores\", memory as \"Memory\", operability as \"Operability\", oper_state as \"Operational State\", oper_state_code, num_vEths as \"# vEth\", num_vFCs as \"# vFC\" FROM \"autogen\".\"BladeServers\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY \"service_profile\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic - location",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Traffic - Total",
     "type": "graph",
     "description": "Combined Ethernet TX/RX traffic across all UCS domains at $location location(s)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"bytes_rx_delta\")  *8/ [[polling_interval]] AS \"RX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"bytes_tx_delta\")  *8/ [[polling_interval]] AS \"TX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      }
     ]
    },
    {
     "title": "FC Traffic - Total",
     "type": "graph",
     "description": "Combined FC TX/RX traffic across all UCS domains at $location location(s)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"bytes_rx_delta\")  *8/ [[polling_interval]] AS \"RX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"bytes_tx_delta\")  *8/ [[polling_interval]] AS \"TX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      }
     ]
    },
    {
     "title": "Top Ethernet traffic - Ingress - per location breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy locations, AKA top-talker and bottom-talker locations\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,location fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Ingress - per location breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy locations, AKA top-talker and bottom-talker locations\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,location fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Ethernet traffic - Egress - per location breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy locations, AKA top-talker and bottom-talker locations\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,location fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Egress - per location breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy locations, AKA top-talker and bottom-talker locations\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,location fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic - domain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Ethernet traffic - Ingress - per domain breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS domains, AKA top-talker and bottom-talker domains\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,domain fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Ingress - per domain breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS domains, AKA top-talker and bottom-talker domains\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,domain fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Ethernet traffic - Egress - per domain breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS domains, AKA top-talker and bottom-talker domains\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,domain fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Egress - per domain breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS domains, AKA top-talker and bottom-talker domains\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport,domain fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic - Chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Ethernet traffic - Ingress - per chassis breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS chassis, AKA top-talker and bottom-talker chassis\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain $tag_chassis",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time(1m),transport,domain,chassis fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Ingress - per chassis breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS chassis, AKA top-talker and bottom-talker chassis\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain $tag_chassis",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time(1m),transport,domain,chassis fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Ethernet traffic - Egress - per chassis breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy UCS chassis, AKA top-talker and bottom-talker chassis\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain $tag_chassis",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time(1m),transport,domain,chassis fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Egress - per chassis breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_domain $tag_chassis",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time(1m),transport,domain,chassis fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic - Service Profile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Eth traffic - Ingress - per service profile breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time(1m),transport,domain,chassis,service_profile fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Ingress - per service profile breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"mean\") AS \"RX Traffic\" from (SELECT mean(\"bytes_rx_delta\") *8/[[polling_interval]] FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time($__interval),domain,chassis,service_profile,vif_name fill(linear)) where $timeFilter GROUP BY time($__interval),transport,domain,chassis,service_profile  fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Eth traffic - Egress - per service profile breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time(1m),transport,domain,chassis,service_profile fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top FC traffic - Egress - per service profile breakdown",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transport $col $tag_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"VnicStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time(1m),transport,domain,chassis,service_profile fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ethernet CRC, Discards, etc.",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"crc_rx_delta\")  / [[polling_interval]] AS \"RX CRC\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"discard_rx_delta\")  / [[polling_interval]] AS \"RX Discards\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"discard_tx_delta\") / [[polling_interval]] AS \"TX Discards\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'Eth' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      }
     ]
    },
    {
     "title": "FC CRC, Discards, etc.",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"crc_rx_delta\")  / [[polling_interval]] AS \"RX CRC\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"discard_rx_delta\")  / [[polling_interval]] AS \"RX Discards\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"discard_tx_delta\")  / [[polling_interval]] AS \"TX Discards\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"link_failures_delta\")  / [[polling_interval]] AS \"Link Failures\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"signal_losses_delta\")  / [[polling_interval]] AS \"Signal losses\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      },
      {
       "alias": "$col $tag_transport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT sum(\"sync_losses_delta\")  / [[polling_interval]] AS \"Sync losses\" FROM \"FIUplinkPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"transport\" = 'FC' AND \"channel\" != '') AND $timeFilter GROUP BY time(1m),transport fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Congestion monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "PAUSE against inbound traffic (RX Pause) on server ports",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: High-level indication of congestion at the selected location(s)\n\n<span style=\"color:orange\">**How to use**</span>: Look for a sustained spike in PAUSE frame rate which is a an indication of congestion. This data is not conclusive due to averaging over a location. To find the exact point of congestion, continue digging further into location > Domain > Chassis > Service profile.\n\n<span style=\"color:orange\">**Details**</span>:\n - The graph show PAUSE frame on FI server ports which are connected to IOM.\n - PAUSE frames are sent by a traffic receiver when it is unable to receive the traffic at the incoming rate.\n - Focus on (sustained) spikes only because PAUSE frames may be exchanged under normal condition also.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT non_negative_derivative(sum(\"pause_rx\"),1s) AS \"PAUSE against Inbound Traffic\" FROM \"FIServerPortStats\" WHERE \"location\" =~ /^$location$/ AND $timeFilter GROUP BY time(1m),location fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      }
     ]
    },
    {
     "title": "PAUSE against outbound traffic (TX Pause) on server ports",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: High-level indication of congestion at the selected location\n\n<span style=\"color:orange\">**How to use**</span>: Look for a sustained spike in PAUSE frame rate which is a an indication of congestion. This data is not conclusive due to averaging over a location. To find the exact point of congestion, continue digging further into location > Domain > Chassis > Service profile.\n\n<span style=\"color:orange\">**Details**</span>:\n - The graph show PAUSE frame on FI server ports which are connected to IOM.\n - PAUSE frames are sent by a traffic receiver when it is unable to receive the traffic at the incoming rate.\n - Focus on (sustained) spikes only because PAUSE frames may be exchanged under normal condition also.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_location",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT non_negative_derivative(sum(\"pause_tx\"),1s) AS \"PAUSE\" FROM \"FIServerPortStats\" WHERE \"location\" =~ /^$location$/ AND $timeFilter GROUP BY time(1m),location fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *8/ [[polling_interval]]" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$location$/" },
        { "condition": "AND", "key": "transport", "operator": "=", "value": "Eth" },
        { "condition": "AND", "key": "channel", "operator": "!=", "value": "''" }
       ]
      }
     ]
    }
   ]
  }
 ]
}