{
 "title": "Chassis PAUSE frame monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from FIEnvStats with key=domain"
   },
   {
    "name": "fi_id",
    "label": "FI ID (A or B)",
    "query": "show tag values from FIServerPortStats with key=fi_id where domain =~ /$domain/"
   },
   {
    "name": "server_port",
    "label": "Server Port",
    "query": "show tag values from FIServerPortStats with key=port where domain =~ /$domain/ and fi_id =~ /$fi_id/ and channel != ''"
   },
   {
    "name": "chassis",
    "label": "Chassis",
    "query": "show tag values from FIServerPortStats with key=to_chassis where domain =~ /$domain/ and fi_id =~ /$fi_id/ and port =~ /$server_port/"
   },
   {
    "name": "bp_port",
    "label": "Backplane Port",
    "query": "show tag values from BackplanePortStats with key=bp_port where domain =~ /$domain/ and fi_id =~ /$fi_id/ and chassis =~ /$chassis/ and channel != ''"
   },
   { "name": "polling_interval", "query": "60" }
  ]
 },
 "panels": [
  {
   "title": "PAUSE frame monitoring on UCS FI server and IOM backplane ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<table style=\"margin-left: auto; margin-right: auto;\" border=\"0\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' width=\"300\" />\r\n<script>\r\n  document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + \"/your_logo.png\");\r\n</script>\r\n</td>\r\n<td style=\"width: 70%;\">\r\n<h2 style=\"text-align: center;\"><span style=\"text-decoration: underline; color: #299c46;\"><strong>(your name) - UCS Traffic Monitoring - Detailed Congestion monitoring</strong></span></h2>\r\n</td>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' alt=\"\" width=\"160\" />\r\n<script>\r\n  document.getElementById('cisco_logo').setAttribute('src', 'http://' + window.location.hostname + \"/cisco_logo.png\");\r\n</script>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"text-align: left;\"></p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "content": "<h1 style=\"text-align: center;\">Congestion against inbound traffic</h1>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "content": "<h1 style=\"text-align: center;\">Congestion against outbound traffic</h1>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FI-A - Server port - RX PAUSE monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port from $tag_to_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "to_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "select": [
      [
       { "params": [ "pause_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "RX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Server port - TX PAUSE monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port to $tag_to_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "to_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "select": [
      [
       { "params": [ "pause_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "TX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Server port - RX PAUSE monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port from $tag_to_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "to_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "select": [
      [
       { "params": [ "pause_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "RX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Server port - TX PAUSE monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port to $tag_to_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "to_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "select": [
      [
       { "params": [ "pause_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "TX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "Chassis Internal congestion - $chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "chassis",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
     "content": "<h1 style=\"text-align: center;\">Congestion against inbound traffic</h1>",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
     "content": "<h1 style=\"text-align: center;\">Congestion against outbound traffic</h1>",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane port RX PAUSE stats in $chassis via FI-A",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port from $tag_to_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "to_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port TX PAUSE stats in $chassis via FI-A",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port to $tag_to_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "to_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port RX PAUSE stats in $chassis via FI-B",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port from $tag_to_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "to_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port RX PAUSE stats in $chassis via FI-B",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port to $tag_to_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "to_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PAUSE stats vs traffic - size to side comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "bp_port",
   "collapsed": true,
   "panels": [
    {
     "title": "Backplane port $bp_port RX PAUSE in $chassis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "$chassis - vIFs connected to Backplane port $bp_port usage stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "iom_backplane_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port $bp_port TX PAUSE in $chassis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "$chassis - vIFs connected to Backplane port $bp_port usage stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "iom_backplane_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}