{
 "title": "UCS Chassis - traffic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "polling_interval", "query": "60" },
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from FIEnvStats with key=domain"
   },
   {
    "name": "chassis",
    "label": "Chassis",
    "query": "show tag values from BackplanePortStats with key=chassis where domain =~ /$domain/"
   },
   {
    "name": "bp_port",
    "label": "Backplane Ports",
    "query": "show tag values from BackplanePortStats with key=bp_port where domain =~ /$domain/ and chassis =~ /$chassis/"
   },
   {
    "name": "domain_name",
    "query": "SELECT \"name\" FROM \"autogen\".\"FIEnvStats\" WHERE \"domain\" =~ /^$domain$/"
   },
   {
    "name": "domain_location",
    "query": "select location from (select location,last(load) from FIEnvStats where (\"domain\" =~ /^$domain$/))"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview for $chassis in $domain_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<table style=\"margin-left: auto; margin-right: auto;\" border=\"0\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' width=\"300\" />\r\n<script>\r\n  document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + \"/your_logo.png\");\r\n</script>\r\n</td>\r\n<td style=\"width: 70%;\">\r\n<h2 style=\"text-align: center;\"><span style=\"text-decoration: underline; color: #299c46;\"><strong>(your name) - UCS Traffic Monitoring - Chassis</strong></span></h2>\r\n<p style=\"text-align: center;\">Use this page for detailed traffic monitoring of the selected UCS Chassis</p>\r\n</td>\r\n<td style=\"width: 15%;\" valign=\"top\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' alt=\"\" width=\"160\" />\r\n<script>\r\n  document.getElementById('cisco_logo').setAttribute('src', 'http://' + window.location.hostname + \"/cisco_logo.png\");\r\n</script>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"text-align: left;\"></p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "content": "<h1 style=\"text-align: center;\"><span style=\"color: #FFFFFF;\"><span style=\"color: #B877D9;\">$chassis </span>in UCS Domain<span style=\"color: #B877D9;\"> $domain_name</span> with IP <span style=\"color: #B877D9;\"> $domain</span> located in <span style=\"color: #B877D9;\"> $domain_location</span></span></h1>\n",
   "targets": [
    {
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Eth traffic - Inbound - per service profile breakdown",
   "type": "graph",
   "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_transport $col $tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time($__interval),transport,service_profile fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Eth traffic - Outbound - per service profile breakdown",
   "type": "graph",
   "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_transport $col $tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time($__interval),transport,service_profile fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top FC traffic - Inbound - per service profile breakdown",
   "type": "graph",
   "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_transport $col $tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time($__interval),transport,service_profile fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top FC traffic - Outbound - per service profile breakdown",
   "type": "graph",
   "description": "<span style=\"color:orange\">**Use Case**</span>: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n<span style=\"color:orange\">**How to use**</span>: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_transport $col $tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time($__interval),transport,service_profile fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[  IOM Fabric port <--> FI Server port  ] Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "FI-A Server ports connected to [[chassis]]",
     "type": "table",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Find links between Fabric Interconnect server ports and fabric ports on IOM in a UCS Chassis\n\n<span style=\"color:orange\">**How to use**</span>: The table is a quick-reference which can further be used at other places for detailed troubleshooting.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(oper_state) as \"Operational State\",to_iom_slot , to_iom_port  FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/) AND (\"to_chassis\" =~ /^$chassis$/) AND fi_id = 'A' AND $timeFilter GROUP BY \"fi_id\",port ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-B Server ports connected to [[chassis]]",
     "type": "table",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Find links between Fabric Interconnect server ports and fabric ports on IOM in a UCS Chassis\n\n<span style=\"color:orange\">**How to use**</span>: The table is a quick-reference which can further be used at other places for detailed troubleshooting.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT  last(oper_state) as \"Operational State\",to_iom_slot , to_iom_port  FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/) AND (\"to_chassis\" =~ /^$chassis$/) AND fi_id = 'B' AND $timeFilter GROUP BY \"fi_id\",port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "[  IOM backplane port <--> Blade Server  ] connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "FI-A Server ports connected to [[chassis]]",
     "type": "table",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Find links between IOM backplane ports and blade server within a UCS chassis\n\n<span style=\"color:orange\">**How to use**</span>: The table is a quick-reference which can further be used at other places for detailed troubleshooting.\n\n<span style=\"color:orange\">**Details**</span>: A blade server can have multiple adaptors. Each adaptor may have multiple ports. Each adaptor port has one-to-one connectivity to IOM backplane port. These connections may or may not be be aggregated under a port-channel.",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT bp_port as \"IOM backplane port\",last(oper_state) as \"Operational State\", channel as \"Port-Channel\", speed as \"Speed\", to_blade as \"To blade\", to_adaptor as \"To adaptor\", adaptor_port as \"To adaptor port\", to_service_profile as \"To Service Profile\" FROM \"autogen\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/) AND (\"chassis\" =~ /^$chassis$/) AND fi_id = 'A' AND channel != '' AND $timeFilter GROUP BY \"fi_id\",bp_port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-B Server ports connected to [[chassis]]",
     "type": "table",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Find links between IOM backplane ports and blade server within a UCS chassis\n\n<span style=\"color:orange\">**How to use**</span>: The table is a quick-reference which can further be used at other places for detailed troubleshooting.\n\n<span style=\"color:orange\">**Details**</span>: A blade server can have multiple adaptors. Each adaptor may have multiple ports. Each adaptor port has one-to-one connectivity to IOM backplane port. These connections may or may not be be aggregated under a port-channel.",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT bp_port as \"IOM backplane port\",last(oper_state) as \"Operational State\", channel as \"Port-Channel\", speed as \"Speed\", to_blade as \"To blade\", to_adaptor as \"To adaptor\", adaptor_port as \"To adaptor port\", to_service_profile as \"To Service Profile\" FROM \"autogen\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/) AND (\"chassis\" =~ /^$chassis$/) AND fi_id = 'B' AND channel != '' AND $timeFilter GROUP BY \"fi_id\",bp_port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Backplane port $bp_port utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "bp_port",
   "collapsed": true,
   "panels": [
    {
     "title": "Backplane port $bp_port utilization - TX",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Monitor the utilization of IOM backplane ports\n\n<span style=\"color:orange\">**How to use**</span>: Start by selecting a UCS domain and chassis. Finally, select a *Backplane port(s)*. The graphs for RX and TX traffic are auto-generated side-by-side. To use the output:\n  - Look at Left Y-axis for utilization in (Giga or Mega) bits per second and Right Y-axis for utilization in %.\n  - *Util Max* shows max speed of the link. *% Max* always shows 100%.\n  - TX traffic on backplane ports is inbound to the blade server. Similarly, RX traffic on backplane ports is outbound from the blade server.\n\nYou can select more than one values or All from *Backplane Ports*. The RX and TX graphs are auto-generated for the selected values. You may want to look at everything when you don't know where to start or if you are just doing routine monitoring. But it is better to focus on one link at a time and not get overwhelmed by too much information at the same time.\n\n<span style=\"color:orange\">**Details**</span>: An IOM backplane port has one-to-one connectivity to a single adaptor port on a blade server. Multiple vNIC/vHBA may be using this link. To find the traffic distribution per vNIC/vHBA, go to the service profile monitoring.\n- The options under *Uplink Port Channel* drop-down are automatically updated based on the selected UCS domain and Chassis",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col $tag_bp_port --> $tag_to_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX Traffic\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port,to_service_profile fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col $tag_bp_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"speed\") *1000000000 AS \"TX MAX\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col $tag_bp_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"speed\")/last(\"speed\") AS \"TX % MAX\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col $tag_bp_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"bytes_tx_delta\") *8/[[polling_interval]]/mean(\"speed\")/1000000000 AS \"TX % Traffic\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane port $bp_port utilization - RX",
     "type": "graph",
     "description": "<span style=\"color:orange\">**Use Case**</span>: Monitor the utilization of IOM backplane ports\n\n<span style=\"color:orange\">**How to use**</span>: Start by selecting a UCS domain and chassis. Finally, select a *Backplane port(s)*. The graphs for RX and TX traffic are auto-generated side-by-side. To use the output:\n  - Look at Left Y-axis for utilization in (Giga or Mega) bits per second and Right Y-axis for utilization in %.\n  - *Util Max* shows max speed of the link. *% Max* always shows 100%.\n  - TX traffic on backplane ports is inbound to the blade server. Similarly, RX traffic on backplane ports is outbound from the blade server.\n\nYou can select more than one values or All from *Backplane Ports*. The RX and TX graphs are auto-generated for the selected values. You may want to look at everything when you don't know where to start or if you are just doing routine monitoring. But it is better to focus on one link at a time and not get overwhelmed by too much information at the same time.\n\n<span style=\"color:orange\">**Details**</span>: An IOM backplane port has one-to-one connectivity to a single adaptor port on a blade server. Multiple vNIC/vHBA may be using this link. To find the traffic distribution per vNIC/vHBA, go to the service profile monitoring.\n- The options under *Uplink Port Channel* drop-down are automatically updated based on the selected UCS domain and Chassis",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col $tag_bp_port <-- $tag_to_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX Traffic\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port,to_service_profile fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col $tag_bp_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"speed\") *1000000000 AS \"RX MAX\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col $tag_bp_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"speed\")/last(\"speed\") AS \"RX % MAX\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col $tag_bp_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"bytes_rx_delta\") *8/[[polling_interval]]/mean(\"speed\")/1000000000 AS \"TX % Traffic\" FROM \"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}