{
 "title": "UCS Domain - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "polling_interval", "query": "60" },
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from FIEnvStats with key=domain"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<table style=\"margin-left: auto; margin-right: auto;\" border=\"0\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' width=\"300\" />\r\n<script>\r\n  document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + \"/your_logo.png\");\r\n</script>\r\n</td>\r\n<td style=\"width: 70%;\">\r\n<h2 style=\"text-align: center;\"><span style=\"text-decoration: underline; color: #299c46;\"><strong>(your name) - UCS Traffic Monitoring - UCS Domain overview</strong></span></h2>\r\n<p style=\"text-align: center;\">Overview of the selected UCS Domain</p>\r\n</td>\r\n<td style=\"width: 15%;\" valign=\"top\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='' alt=\"\" width=\"160\" />\r\n<script>\r\n  document.getElementById('cisco_logo').setAttribute('src', 'http://' + window.location.hostname + \"/cisco_logo.png\");\r\n</script>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"text-align: left;\"></p>"
  },
  {
   "title": "UCS Domain name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 5, "y": 3 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "# Chassis - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Blade servers and operational state",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(service_profile) AS \"OK\" from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/ AND \"oper_state\" = 'ok') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "oper_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Operation state - UP" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "oper_state", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(service_profile) AS \"Other\" from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/ AND \"oper_state\" != 'ok') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "oper_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "oper_state", "operator": "!=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "select location from (select location,last(load) from FIEnvStats where (\"domain\" =~ /^$domain$/))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "# CPUs - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_cpus\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# CPU cores - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_cores\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_cores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# vFC - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_vFCs\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_vFCs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# vEth - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"num_vEths\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "num_vEths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) from (SELECT last(\"memory\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "# blades - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(service_profile) from (SELECT last(\"model\") FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "content": "<h1 style=\"text-align: center;\">FI-A</h1>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "content": "<h1 style=\"text-align: center;\">FI-B</h1>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FI-A",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "oob_if_ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OOB IP Address" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-A memory utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT (last(\"total_memory\") - last(\"mem_available\"))/last(\"total_memory\")*100 FROM \"autogen\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /A/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Mem total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "SELECT last(\"total_memory\")  FROM \"autogen\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /A/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-B",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "oob_if_ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OOB IP Address" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "FI-B Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "FI-B memory utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT (last(\"total_memory\") - last(\"mem_available\"))/last(\"total_memory\")*100 FROM \"autogen\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /B/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-B Mem total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "SELECT last(\"total_memory\")  FROM \"autogen\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /B/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Mem avail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "SELECT last(\"mem_available\")  FROM \"autogen\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /A/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-B Mem avail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "SELECT last(\"mem_available\")  FROM \"autogen\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /B/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Network and other ports - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' and \"fi_id\" =~ /A/) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Network and other ports - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' and \"fi_id\" = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Distribution - Operational state - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND \"fi_id\" = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Not UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" != 'up' AND \"fi_id\" = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Distribution - Transport - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"FC\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"transport\" = 'FC' AND \"fi_id\" = 'A' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Ethernet\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"transport\" = 'Eth' AND \"fi_id\" = 'A' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Distribution - Operational state - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND \"fi_id\" = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Not UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" != 'up' AND \"fi_id\" = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Distribution - Transport - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"FC\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"transport\" = 'FC' AND \"fi_id\" = 'B' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Ethernet\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"transport\" = 'Eth' AND \"fi_id\" = 'B' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Distribution - Ethernet - Speed - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 1) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 10) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 40) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Distribution - FC - Speed - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 4 AND \"fi_id\" = 'A' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 8 AND \"fi_id\" = 'A' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 16 AND \"fi_id\" = 'A' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Distribution - Ethernet - Speed - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 1) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 10) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 40) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Distribution - FC - Speed - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 4 AND \"fi_id\" = 'B' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 8 AND \"fi_id\" = 'B' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 16 AND \"fi_id\" = 'B' ) and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Server ports - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND fi_id = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Server ports - $domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND fi_id = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Distribution - Operational state - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND fi_id = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Not UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" != 'up' AND fi_id = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Distribution - operational speed - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 1 AND fi_id = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 10 AND fi_id = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 40 AND fi_id = 'A') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Distribution - Operational state - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND fi_id = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Not UP\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_state\" != 'up' AND fi_id = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Distribution - operational speed - $domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 1 AND fi_id = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 10 AND fi_id = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"autogen\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"channel\" != '' AND \"oper_speed\" = 40 AND fi_id = 'B') and $timeFilter group by domain,fi_id,port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Blade servers",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT location as \"Location\", domain as \"Domain\",  chassis as \"Chassis ID\", blade as \"Blade\", model as \"Model\", serial as \"Serial\", num_cpus as \"# CPU\", num_cores as \"# Cores\", memory as \"Memory\", operability as \"Operability\", oper_state as \"Operational State\", oper_state_code, num_vEths as \"# vEth\", num_vFCs as \"# vFC\" FROM \"autogen\".\"BladeServers\" WHERE (\"domain\" =~ /^$domain$/) AND $timeFilter GROUP BY \"service_profile\",chassis,blade order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}